export const data = {
  name: 'KIMANI\nMUKUNDI',
  initials: 'KM',
  tagline: ['SOFTWARE DEVELOPER', 'ML ENGINEER', 'PROBLEM SOLVER'],
  email: 'kimanimukundi605@gmail.com',
  phone: '+254 797 325 474',
  githubs: ['github.com/kyatrixxkush', 'github.com/kimanimukundi'],
  location: 'Nairobi, Kenya',
  stats: [
    { num: '8+', label: 'Projects Shipped' },
    { num: '4+', label: 'Tech Domains' },
    { num: '2026', label: 'BSc Graduate' },
  ],
  about: [
    "I'm a final-year Information Technology student at Zetech University with a strong interest in building real, working tech solutions.",
    "Over time I've developed hands-on experience across software development, data analysis, machine learning, and full-stack web development — all through personal projects I've shipped end to end.",
    "I've built and deployed 8 projects so far, including web apps, APIs, machine learning models, and data-driven tools. I enjoy learning by doing, and I'm currently looking for an internship where I can contribute, grow, and gain real industry experience.",
    "I care about writing clean, readable code and I'm comfortable working across the full development process — from idea to deployment.",
  ],
  tech: [
    'Python', 'Java', 'C++', 'HTML / CSS',
    'Flask', 'scikit-learn', 'Pandas', 'Matplotlib',
    'BeautifulSoup', 'SQLite / SQL', 'REST APIs', 'Machine Learning',
    'NLP', 'Streamlit', 'Git & GitHub', 'Render / Cloud',
    'VS Code', 'Linux',
  ],
  education: [
    {
      degree: 'BSc Information Technology',
      school: 'Zetech University',
      meta: 'Nairobi, Kenya · Expected Graduation: 2026',
      desc: 'Relevant coursework: Data Structures & Algorithms, Database Systems, Software Engineering, Computer Networks, Object-Oriented Programming. Currently completing final year project.',
    },
  ],
  projects: [
    {
      num: '01',
      label: 'FEATURED PROJECT · DEPLOYED',
      title: 'Student Performance Prediction System',
      highlight: '89% accuracy (R²=0.89) · 90% precision · 88% recall',
      desc: 'An interpretable ML framework that predicts student academic performance across diverse university assessment structures. Supports any configuration (CATs, quizzes, midterms, projects) without code changes. Validated across 3 datasets ranging from 200 to 50,000 students with 5-fold cross-validation.',
      tags: ['Python', 'Scikit-learn', 'Random Forest', 'Streamlit', 'Pandas', 'Plotly', 'YAML'],
      links: [
        { label: 'GitHub', href: 'https://github.com/kyatrixxkush/Student-Performance-Prediction-System' },
        { label: 'Live Demo', href: 'https://student-performance-prediction-system-edfinrdxt4dqcg6i63n43h.streamlit.app/' },
      ],
    },
    {
      num: '02',
      label: 'FEATURED PROJECT · DEPLOYED',
      title: 'AI CV Analyzer',
      highlight: null,
      desc: "An AI-powered web app that analyzes CVs against job descriptions using OpenAI's GPT API. Users upload a CV (PDF or DOCX) and paste a job description to receive a detailed match score, missing keywords, and actionable improvement suggestions. Handles complex PDF parsing and generates insights in seconds.",
      tags: ['Python', 'Flask', 'OpenAI API', 'PyPDF2', 'pdfplumber', 'Render'],
      links: [
        { label: 'Live Demo', href: 'https://ai-powered-cv-analyzer.onrender.com/' },
      ],
    },
    {
      num: '03',
      label: 'FEATURED PROJECT · DEPLOYED',
      title: 'Nairobi Live Dashboard',
      highlight: null,
      desc: 'A live, mobile-friendly dashboard pulling real-time data from multiple APIs — weather, news, and exchange rates. Fully deployed on Render with automatic updates every 5 minutes.',
      tags: ['Python', 'Flask', 'REST APIs', 'HTML/CSS', 'Render'],
      links: [
        { label: 'GitHub', href: 'https://github.com/kyatrixxkush/nairobi-dashboard' },
        { label: 'Live Demo', href: 'https://nairobi-dashboard-mi16.onrender.com/' },
      ],
    },
    {
      num: '04',
      label: 'PROJECT',
      title: 'Sentiment Analysis — NLP Text Classifier',
      highlight: null,
      desc: 'A machine learning model that classifies product reviews as positive, negative, or neutral. Used TF-IDF and bigrams across multiple models with a real-time prediction interface and visual performance metrics.',
      tags: ['Python', 'scikit-learn', 'NLP', 'TF-IDF', 'Pandas'],
      links: [
        { label: 'GitHub', href: 'https://github.com/kyatrixxkush/sentiment-analysis' },
      ],
    },
    {
      num: '05',
      label: 'PROJECT',
      title: 'House Price Prediction Model',
      highlight: null,
      desc: 'ML model predicting Nairobi house prices based on location, size, and other features. Tested multiple models, selected the best-performing one, and built a full preprocessing and prediction pipeline.',
      tags: ['Python', 'scikit-learn', 'Pandas', 'Matplotlib'],
      links: [
        { label: 'GitHub', href: 'https://github.com/kyatrixxkush/ml-model' },
      ],
    },
    {
      num: '06',
      label: 'PROJECT',
      title: 'Books REST API',
      highlight: null,
      desc: 'A RESTful API with full CRUD functionality, filtering, structured JSON responses, and a test suite to ensure all endpoints work correctly.',
      tags: ['Python', 'Flask', 'REST API', 'SQLite'],
      links: [
        { label: 'GitHub', href: 'https://github.com/kyatrixxkush/rest-api' },
      ],
    },
    {
      num: '07',
      label: 'PROJECT',
      title: 'Task Manager Web App',
      highlight: null,
      desc: 'A functional task management app with create, edit, filter, and delete features. Built with MVC architecture and persistent data storage using SQLite.',
      tags: ['Python', 'Flask', 'SQLite', 'HTML/CSS', 'MVC'],
      links: [
        { label: 'GitHub', href: 'https://github.com/kyatrixxkush/todo-app' },
      ],
    },
    {
      num: '08',
      label: 'PROJECT',
      title: 'Kenya Tech Sales Data Analysis',
      highlight: null,
      desc: 'Analyzed 500 sales records using Pandas to surface insights — total revenue, top products, regional performance — with visualizations to make data easy to interpret.',
      tags: ['Python', 'Pandas', 'Matplotlib', 'Data Analysis'],
      links: [],
    },
  ],
  skills: [
    { name: 'Python', pct: 92 },
    { name: 'Machine Learning', pct: 85 },
    { name: 'Flask / APIs', pct: 83 },
    { name: 'Data Analysis', pct: 80 },
    { name: 'SQL / SQLite', pct: 76 },
    { name: 'HTML / CSS', pct: 72 },
    { name: 'Java', pct: 65 },
    { name: 'Git & GitHub', pct: 80 },
  ],
}
